"""price prev_close+fetched_at, cash_flows

Revision ID: 4b11b93201a4
Revises: 9f3a2c1d7e55
Create Date: 2026-10-02 15:05:44.313995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '4b11b93201a4'
down_revision: Union[str, None] = '9f3a2c1d7e55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_flows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('note', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('price_snapshots', sa.Column('prev_close', sa.Float(), nullable=True))
    op.add_column('price_snapshots', sa.Column('fetched_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price_snapshots', 'fetched_at')
    op.drop_column('price_snapshots', 'prev_close')
    op.drop_table('cash_flows')
    # ### end Alembic commands ###
